### ISSUE TITLE
Q: How to read bash error message

### ISSUE THREAD

**Issue by iDevo** [Frugghi/SwiftSH#13]
Hi there! 
Just a quick question. When you execute something like "foo bar" there occurs of course a bash error which is returned via a SSHError.Command.execError:

```
// Command
public enum Command: Error {
    case execError(String?, Data)
}
```

The printed error looks like: 
```
execError : 2 elements
      ▿ .0 : Optional<String>
        - some : "bash: foo: command not found\n"
      ▿ .1 : 29 bytes
          ...
```

I'd like to access the error message "bash: foo: command not found\n", but I wasn't able to get it working.

Any hint is highly appreciated :-)
Thanks in advance!

**Comment by Frugghi** [comment]
You should be able to get it by doing something like this:
```Swift
if case SSHError.Command.execError(let message, _) = error {
    // Here message will have the string you need
}
```
