### ISSUE TITLE
SIGABRT in SSHQueue

### ISSUE THREAD

**Issue by iDevo** [Frugghi/SwiftSH#5]
Hi Frugghi, 
first of all thank you very much (again) for your great work! I've just implemented the library in a productive App, which was a great success all in all. 

I'm using Firebase / Crashlytics and there is just a single crash, which is occurring in 10% of the current users (iPhone 6-X, iPad Air / Pro).
I've collected 30 instances of the crash (all identical), unfortunately I've not a lot details on this crash (like executed command or host information) and I'm not able to export a whole crash log, so I'd like to share it simply using copy & paste.

Hope these little information may help.
Again, I think it's great that there is just a single crash in such a complex project so far - great work!
 I'll dig deeper using the FB log functions in further releases, maybe I can identify the bug. 

The crash (SIGABRT ABORT) takes place in number 6.

```
Crashed: SSH Queue #1
SIGABRT ABORT 0x000000018368d2ec
keyboard_arrow_up
0
libsystem_kernel.dylib
__pthread_kill + 8
1
libsystem_pthread.dylib
<redacted> + 376
2
libsystem_c.dylib
abort + 140
3
libswiftCore.dylib
swift_vasprintf(char**, char const*, char*) + 54
4
libswiftCore.dylib
swift_getDefaultErrorCode + 50
5
libswiftCore.dylib
swift_unownedRetainStrong + 124
arrow_right 

6
SwiftSH
_T07SwiftSH10SSHCommandC7executeySS_ySS_10Foundation4DataVSgs5Error_pSgtcSg10completiontFyyKcfU0_yycfU0_TA + 40

7
SwiftSH
_T0Ix_IyB_TR + 36
8
libdispatch.dylib
<redacted> + 24
9
libdispatch.dylib
<redacted> + 16
10
libdispatch.dylib
<redacted> + 424
11
libdispatch.dylib
<redacted> + 1020
12
libdispatch.dylib
<redacted> + 280
13
libdispatch.dylib
<redacted> + 336
14
libdispatch.dylib
<redacted> + 340
15
libdispatch.dylib
<redacted> + 668
16
libsystem_pthread.dylib
_pthread_wqthread + 860
17
libsystem_pthread.dylib
start_wqthread + 4

```

Additional keys:
```
crash_info_entry_0
Fatal error: Attempted to read an unowned reference but object 0x105948870 was already deallocated

crash_info_entry_1
abort() called
```

**Comment by Frugghi** [comment]
I believe this has been fixed now. Feel free to reopen if you're still experiencing the issue!
