### ISSUE TITLE
Make compatible with macOS

### ISSUE THREAD

**Issue by dbuskariol** [Frugghi/SwiftSH#8]
I'd love to use this in my macOS swift app, but I get the following error:

```
[!] The platform of the target `ProjectName` (macOS 10.12) is not compatible with `SwiftSH (0.1.0)`, which does not support `osx`.
```

**Comment by johncederholm** [comment]
Steps to recompile for macOS:

1. Go to the SwiftSH target (not the project!) -> Build Settings and then search for the Base SDK. Switch that to macOS 10.* (usually you'll pick the latest, which is 10.13 at the time of this comment).

2. Now you also need to recompile the external libraries. Follow the author's direction and download this repo
[https://github.com/Frugghi/iSSH2]

3. Go to iSSH2.sh and change line 105 (which should be `BUILD_OSX=false` to `BUILD_OSX=true`.
Then, run the shell command (open Terminal, cd into root folder of the iSSH2 project, and run sh iSSH2.sh if on Mac). This compiles the libraries into a mac-compatible format.

4. Delete the libssh2.a, libcrytpo.a, and libssl.a libraries from the SwiftSH project.

5. Go back to the iSSH2 project folder. Go into openssl->lib and add the libcrypto.a and libssl.a libraries to the SwiftSH project.

6. Go back into the root of the iSSH2 folder and navigate to libssh2->lib and add the libssh2.a library to the SwiftSH project.

You should be up and running on mac now. If you still have problems, I recommend going to SwiftSH and making sure that SwiftSH(Target)->Build Phases->Link Binary With Libraries includes the 3 libraries we added above.

Making a project that is macOS and iOS-compatible is waaaaaay harder, but you can find out how via tutorials online as well as what I said. I suggest we close this issue if this solves your problem.

**Comment by MichaelSwag** [comment]
i don't understand step 2 when i do this and run "pod install" i get the error again ''[!] The platform of the target `Quotes` (macOS 10.11) is not compatible with `SwiftSH (0.1.2)`, which does not support `osx`.
"

**Comment by MichaelSwag** [comment]
Okay ill try to do that, thanks!

**Comment by MichaelSwag** [comment]
Did not get it to work..
